name: Build and Push to Docker Hub

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t asjalamir/chai-backend:latest .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u asjalamir --password-stdin

      - name: Push to Docker Hub
        run: docker push asjalamir/chai-backend:latest

      - name: Trigger Render redeploy
        run: curl -X POST https://api.render.com/deploy/srv-d07s8kidbo4c73brp0c0?key=bnm2ZriMsKE